
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    # url: jdbc:mysql://database-1.cryse64w6ow7.us-east-2.rds.amazonaws.com/projeto
    url: jdbc:mysql://localhost/projeto  
    username: root
    # username: root 
    password: Ru32958305@ 
    # password: password
  jpa:
    hibernate.ddl-auto: update  
    generate-ddl: true
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect